name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Command line
        run: |
          id
          echo $PATH
          brew list --versions
      - name: Python
        run: |
          which python2.7
          ls -l $(which python 2.7)
          python2.7 --version
          which python3
          ls -l $(which python3)
          python3 --version
          which python3.7
          ls -l $(which python3.7)
          python3.7 --version
      - name: Default Xcode
        run: |
          xcode-select -p
          xcodebuild -version
      - name: Set Xcode to 11.5
        run: |
          sudo xcode-select -s /Applications/Xcode_11.5.app/Contents/Developer
          xcodebuild -version
      - name: MacPorts
        uses: WildbookOrg/wbia-pypkg-build/actions/macports@v1.0.0
      - name: Install example port and check version of Cmake
        run: |
          port version
          sudo port selfupdate
          port version
          ls -al $(which cmake)
          cmake --version
          sudo port -vs install eigen3-devel
          ls -al /opt/local/var/macports/software/
      - name: Upload MacPorts artifact
        uses: actions/upload-artifact@master
        with: 
          name: macports
          path: /opt/local/